### ISSUE TITLE
fx-CG50 compatibility

### ISSUE THREAD

**Issue by critor** [maxwrlr/Bomberman-for-CasioFXCG20#1]
Seems your reupload did kill my issue ?...

Please add fx-CG50 compatibility.

You just need to dynamically get and use the VRAM address, instead of using the hard coded value which is wrong for the newer fx-CG50 _(which thus only displays texts with the current build)_ :
`void* GetVRAMAddress()
{
   __asm__("mov.l syscall_adress, r2\n"
       "mov.l getVRAM, r0\n"
       "jmp @r2\n"
       "nop\n"
       "syscall_adress: .long 0x80020070\n"
       "getVRAM: .long 0x01E6");
}`

I'll gladly test and confirm you it works when done.

Regards.

**Comment by maxwrlr** [comment]
Thanks for filing this issue! It should be fixed now.

**Comment by critor** [comment]
Thanks for your prompt fix; yes it works perfectly now.
